python extract_evit.py work_dir_modalities3D/3D/medsam_lite_best.pth models/3D.pth
python extract_evit.py work_dir_modalities3D/Dermoscopy/medsam_lite_best.pth models/Dermoscopy.pth
python extract_evit.py work_dir_modalities3D/Endoscopy/medsam_lite_best.pth models/Endoscopy.pth
python extract_evit.py work_dir_modalities3D/Fundus/medsam_lite_best.pth models/Fundus.pth
python extract_evit.py work_dir_modalities3D/Mammography/medsam_lite_best.pth models/Mammography.pth
python extract_evit.py work_dir_modalities3D/Microscopy/medsam_lite_best.pth models/Microscopy.pth
python extract_evit.py work_dir_modalities3D/OCT/medsam_lite_best.pth models/OCT.pth
python extract_evit.py work_dir_modalities3D/US/medsam_lite_best.pth models/US.pth
python extract_evit.py work_dir_modalities3D/XRay/medsam_lite_best.pth models/XRay.pth
